### PR TITLE
Added User schema

### LINKED ISSUE #13: User signup and login[Feature Request]:
### Description

We can have user signup and login  which later we can use to show all his shorten URLs

### Domain

Server - (Express)

### Code of Conduct

- [X] I follow [Code of Conduct](https://github.com/vigneshshettyin/EatMyURL/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by AdnanMuzavor**
Added API for signup
Added API for login
Used JWT for token generation

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
->Added backend schema and API for user sign-up
->AT later stage when user signs up and login
->We can show all links shortened by User by linking URL schema with user posting it
->This will make good use of URL's stored in DB

Fixes #13

<hr>

## Domain of Contribution 📊

- [x] Documentation
- [ ] Android (Flutter)
- [x] Backend (Express)

<hr>

## Checklist ✅

- [x] I follow [Code of Conduct](https://github.com/vigneshshettyin/EatMyURL/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

Link: showing working of APIs -> https://www.recordjoy.com/view/XnyFGLw7eSbKLhWBCvAK

<hr>

### CODE REVIEW

**Review by vigneshshettyin — CHANGES_REQUESTED** [review]
Thanks for raising a pr @AdnanMuzavor.

Please focus on these changes
-> Don't return the password to user.
-> Add some parameters which stores the id's of users links.
-> Use concept of access and refresh token. Keep the expiry time a day and push the access token to a blacklist table once the access token is expired. 
-> Use proper email validation by using either validator library or joi (https://joi.dev/)
-> Also, restrict user to use strong password look for Regular Expressions(https://regexr.com/3bfsi)

Kindly make these changes and raise a pr. 

Thanks!

**Comment by AdnanMuzavor** [comment]
Okay sir, I'll try to work on above changes.

By the way for second point, I feel it's better to keep user field in links (Schema, which can be populated later) as later we can return links my directly filtering from mongoDB based on userid.

is it fine sir?

**Comment by vigneshshettyin** [comment]
> directly filtering from mongoDB based on userid.

Yes, @AdnanMuzavor that works!

**Comment by AdnanMuzavor** [comment]
Hey  @vigneshshettyin  due to offline college I am bust.
In this pull request I have introduced refresh token and validation for user as per mentioned by you.

Further for authentication of user and that of token I'll raise pull request in few days. I should do same for linking User with URLs, please don't mind.

**Review by vigneshshettyin — APPROVED** [review]
Thanks for contributing, @AdnanMuzavor!

**Pull request merged**
