### PR TITLE
added download qr feature

### PR DESCRIPTION
**Pull request by VijeshVS**

### CODE REVIEW

**Review by vigneshshettyin — CHANGES_REQUESTED** [review]
Try if you are able to support download in SVG/JPG as well. This should be possible according to me just give a try

**Comment by VijeshVS** [comment]
added jpeg download option in the latest commit. Since the element is CANVAS it is not possible to download it as a SVG file. To do that we need to convert CANVAS to SVG and do some computation.

**Comment by vigneshshettyin** [comment]
PNG and JPG works for us!

**Review by vigneshshettyin — APPROVED** [review]
LGTM!

**Pull request merged**
