### PR TITLE
Added signup,login and navbar

### PR DESCRIPTION
**Pull request by AdnanMuzavor**
<hr>

Added
>> navbar, signup and login page
>> used materialUI for inputs and buttons
>> Functions are same as v1
>> Made UI same as that of landing page

<hr>

## Domain of Contribution 📊

- [x] Documentation
- [ ] Android (Flutter)
- [ ] Backend (Express)

<hr>

## Checklist ✅

- [x] I follow [Code of Conduct](https://github.com/vigneshshettyin/EatMyURL/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif 📸
Screen recording showing demo: https://www.recordjoy.com/view/oR4FfdfhKsTcdCrcET02
<hr>

### CODE REVIEW

**Comment by seifibrahim32** [comment]
@AdnanMuzavor @ImgBotApp @data-charya @vigneshshettyin can i contribute or the admins of project arent available?

**Comment by AdnanMuzavor** [comment]
Hey @vigneshshettyin I hope you pull request is fine.
Was waiting for your response!!

**Comment by AdnanMuzavor** [comment]
Hey @vigneshshettyin I hope the pull request is fine.
Was waiting for your response!!

**Review by vigneshshettyin — CHANGES_REQUESTED** [review]
Hi, I have reviewed your pull request. Changes required in UI need to match our current application UI. I want to list some fundamental changes.

1. Alignment of edit text and also buttons.
2. Extra large logo.
3. Navbar is not required it could be replaced with a floating auth button. 

@AdnanMuzavor

**Comment by AdnanMuzavor** [comment]
Okay @vigneshshettyin .
I'll make the logo more bigger.
By the way could you clarify which edit text button you're talking about?

**Comment by AdnanMuzavor** [comment]
@vigneshshettyin ,I hope it's proper this time. I know you're busy with college and same here too.
Thank you for your time through out the GSSoC'22.
Hoping that this pull request suits.

**Comment by seifibrahim32** [comment]
@[AdnanMuzavor](https://github.com/AdnanMuzavor) kindly please help me in something regarding the configs betwee server and Flutter

**Comment by vigneshshettyin** [comment]
> https://www.recordjoy.com/view/oR4FfdfhKsTcdCrcET02

Kindly provide screen recording @AdnanMuzavor

**Comment by AdnanMuzavor** [comment]
Okay @vigneshshettyin 

https://www.recordjoy.com/view/qvuTAkoqNcoCLFTONopm

**Comment by AdnanMuzavor** [comment]
@seifibrahim32 can you connect with me on linkedin, I'll try to resolve what you need.

**Review by vigneshshettyin — APPROVED** [review]

**Pull request merged**
