### PR TITLE
Added signup/login page

### PR DESCRIPTION
**Pull request by AdnanMuzavor**
Added login page
Created states and Submit functions
Fields missing exception handled
Used material UI for inputs
Made Both components responsive
Created Routes(Navbar handling not done as yet)

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Domain of Contribution 📊

- [x] Documentation
- [ ] Android (Flutter)
- [ ] Backend (Express)

<hr>

## Checklist ✅

- [x] I follow [Code of Conduct](https://github.com/vigneshshettyin/EatMyURL/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif 📸
Link showing demo: https://www.recordjoy.com/view/s9lrW3HrTZjmzJmR48Ed
<hr>

### CODE REVIEW

**Comment by vigneshshettyin** [comment]
This is not accepted you literally copy pasted the same code which was written for v1. @AdnanMuzavor I am closing this issue.

**Comment by AdnanMuzavor** [comment]
Okay @vigneshshettyin .Sorry!! I wasn't knowing that you were expecting different code.
If you could have told that I wouldn't have done this.
Sorry for inconvenience.

**Comment by vigneshshettyin** [comment]
Please don't repeat it this was mentioned by the GSSOC'22 team as well. @AdnanMuzavor

**Comment by AdnanMuzavor** [comment]
Yes I won't do it again @vigneshshettyin !!

**Pull request closed without merging**
